### ISSUE TITLE
Add Comprehensive Documentation for Better Clarity

### ISSUE THREAD

**Issue by Mathious6** [YahyaBouayad/Game-of-Life#4]
Hey @YahyaBouayad ! I've noticed that our project currently lacks detailed documentation, which is essential for new users and contributors to understand its functionality and structure. Since I have some free time, I'd be happy to take on the task of creating comprehensive documentation. This would include a clear introduction to the project, installation and usage instructions, descriptions of each module and their functions, and possibly some examples. Good documentation will significantly enhance the user experience and encourage more contributions to our project. Let me know if you're on board with this idea!

**Comment by YahyaBouayad** [comment]
Hey @Mathious6 ,  I completely agree with your observation. The absence of detailed documentation in the project can indeed be a barrier for new users and contributors.

**Comment by YahyaBouayad** [comment]
Thank you for your contribution !
