### ISSUE TITLE
 Enhance README.md for Better Project Understanding

### ISSUE THREAD

**Issue by Magnoir** [YahyaBouayad/Game-of-Life#7]
Description:

The current README.md for the Python Game of Life project provides a good overview of the prerequisites, installation, and usage. However, it could be improved with a more detailed explanation of the project and expected output.

Details:

Project Explanation: The README.md does not provide a detailed explanation of what the Game of Life is. It would be beneficial for users unfamiliar with the Game of Life to have a brief explanation or a link to an external resource for more information.

Expected Output: The Usage section explains how to run the project but does not describe what the user should expect to see when they run the program. A brief description of the initial state of the grid, how it changes over time, and what a typical output looks like would be helpful.

Suggested Fix:

Enhance the README.md with a detailed explanation of the Game of Life and a description of the expected output when running the program.

**Comment by YahyaBouayad** [comment]
Thank you for the suggestion , i will add detail to how run the program
